SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

IF OBJECT_ID('dbo.DeleteRegistry') IS NULL
	EXEC ('CREATE PROCEDURE dbo.DeleteRegistry AS RETURN 0')
GO

ALTER PROCEDURE dbo.DeleteRegistry
	@ID INT
AS

DELETE FROM Registry
WHERE  ID = @ID