SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

IF OBJECT_ID('dbo.DeleteEvent') IS NULL
	EXEC ('CREATE PROCEDURE dbo.DeleteEvent AS RETURN 0')
GO

ALTER PROCEDURE dbo.DeleteEvent
	@ID          INT
AS

DELETE FROM Event
WHERE  ID = @ID