SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

USE UNEXUS_APPSERVER

CREATE TABLE Registry
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	Event INT,
	Comer INT,

	FOREIGN KEY (Event) REFERENCES Event(ID),
	FOREIGN KEY (Comer) REFERENCES Users(ID)
)